apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/apache
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pvc
  namespace: services
spec:
  storageClassName: ""
  volumeName: apache-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
