apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goprecords-ingress
  namespace: services
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: goprecords.f3s.buetow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goprecords-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goprecords-ingress-lan
  namespace: services
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - goprecords.f3s.lan.buetow.org
      secretName: f3s-lan-tls
  rules:
    - host: goprecords.f3s.lan.buetow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goprecords-service
                port:
                  number: 80
