apiVersion: v1
kind: PersistentVolume
metadata:
  name: miniflux-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nfs/k3svolumes/miniflux/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
