apiVersion: v1
kind: Service
metadata:
  name: miniflux
spec:
  selector:
    app: miniflux-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-postgres
spec:
  selector:
    app: miniflux-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
