apiVersion: v1
kind: PersistentVolume
metadata:
  name: keybr-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/keybr/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keybr-data-pvc
  namespace: services
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
