System hostname = buildvm
Which network interface do you wish to configure = vio0
IPv4 address for vio0 = autoconf
IPv6 address for vio0 = none
Which network interface do you wish to configure = done
DNS domain name = local
Password for root = build123
Setup a user = pbuild
Password for user = build123
Allow root ssh login = no
What timezone are you in = UTC
Which disk is the root disk = sd0
Encrypt the root disk = no
Use (W)hole disk MBR, whole disk GPT, (O)penBSD area or (E)dit = whole
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = a
Location of sets = cd0
Set name(s) = -game*.tgz -x*.tgz
Continue without verification = yes
