apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: player-ingress
  namespace: services
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: player.f3s.buetow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: player-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: player-ingress-lan
  namespace: services
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - player.f3s.lan.buetow.org
      secretName: f3s-lan-tls
  rules:
    - host: player.f3s.lan.buetow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: player-service
                port:
                  number: 8080
