apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xplayer-ingress
  namespace: services
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: xplayer.f3s.buetow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xplayer-service
                port:
                  number: 8080
