apiVersion: v1
kind: PersistentVolume
metadata:
  name: xplayer-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/xplayer/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xplayer-data-pvc
  namespace: services
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xplayer-media-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/xplayer/media
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xplayer-media-pvc
  namespace: services
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
