apiVersion: v1
kind: Service
metadata:
  labels:
    app: xplayer
  name: xplayer-service
  namespace: services
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: xplayer
