apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-demo
  namespace: cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://git-server.cicd.svc.cluster.local/conf.git
    targetRevision: master
    path: f3s/tracing-demo/helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
  # Let Argo Rollouts manage Rollout runtime state
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    # Ignore template env vars (kubectl patch adds env vars for triggering)
    - /spec/template/spec/containers/0/env
    - /spec/template/spec/containers/1/env
    - /spec/template/spec/containers/2/env
    # Ignore status fields (Argo Rollouts manages these)
    - /status
