max connections = 5
timeout = 300

[joernshtdocs]
comment = Joerns htdocs
path = /var/www/htdocs/joern
read only = yes
list = yes
uid = www
gid = www
hosts allow = *.wg0.wan.buetow.org,*.wg0,localhost

[irregular-ninja]
comment = Irregular Ninja photo album (push from k3s over wg0)
path = /var/www/htdocs/irregular.ninja
read only = no
list = yes
uid = www
gid = www
hosts allow = *.wg0.wan.buetow.org,*.wg0,localhost

[alt-irregular-ninja]
comment = Alternative Irregular Ninja photo album (push from k3s over wg0)
path = /var/www/htdocs/alt.irregular.ninja
read only = no
list = yes
uid = www
gid = www
hosts allow = *.wg0.wan.buetow.org,*.wg0,localhost
