// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package rnodes

func (Base) DescFirewalldOff() string {
	return "Keeps firewalld stopped and disabled (decided in task tj2, f3s-k3s install.md)"
}

func (Base) DescHosts() string {
	return "Renders /etc/hosts (stock header, registry.lan -> 127.0.0.1, LAN and wg0 rows from the shared etchosts inventory)"
}

func (Base) DescNvme() string {
	return "Keeps the NVMe initramfs drivers (dracut, rebuilt only on change, no reboot) and lvm.conf use_devicesfile = 0"
}

func (Base) DescSSHD() string {
	return "Installs the sshd auth drop-in (root by key, no passwords), validated with sshd -t; reloads sshd on change"
}

func (Base) DescSelinuxWireguard() string {
	return "Keeps SELinux enforcing with only wireguard_t permissive (semanage permissive -a)"
}

func (K3s) DescConfig() string {
	return "Renders /etc/rancher/k3s/config.yaml (etcd metrics, event-ttl, controller-manager bind, wg0 node-ip/advertise-address); no k3s restart"
}

func (K3s) DescRegistries() string {
	return "Installs /etc/rancher/k3s/registries.yaml (registry.lan.buetow.org:30001 -> http://localhost:30001); no k3s restart"
}

func (Maintenance) DescImageGC() string {
	return "Installs the k3s kubelet image-GC drop-in (collect at 70% disk, down to 60%)"
}

func (Maintenance) DescNFSClientFstab() string {
	return "Manages the /etc/fstab line of the k3s NFS volume mount (no remount)"
}

func (Maintenance) DescNFSClientIdmapd() string {
	return "Sets the NFSv4 id-mapping Domain in /etc/idmapd.conf"
}

func (Maintenance) DescNFSClientPackages() string {
	return "Installs the NFS client packages (stunnel, nfs-utils)"
}

func (Maintenance) DescNFSClientStunnel() string {
	return "Manages the stunnel NFS client config and key permissions (no restart; next boot)"
}

func (Maintenance) DescNFSClientSysctl() string {
	return "Raises fs.inotify.max_user_instances to 512 on r-nodes"
}

func (Maintenance) DescNFSClientUnits() string {
	return "Enables and starts rpcbind and nfs-client.target"
}

func (Maintenance) DescNFSMountMonitor() string {
	return "Installs and enables the r-node NFS mount monitor"
}

func (Maintenance) DescNFSMountpointGuard() string {
	return "Makes the empty directory under the NFS mount immutable (no local writes when NFS is absent)"
}

func (Maintenance) DescPersistentJournal() string {
	return "Enables bounded persistent systemd journals on r-nodes"
}

func (Maintenance) DescRetiredNFSCron() string {
	return "Removes the legacy per-minute check-nfs-mount.sh root cron line (the timer runs it)"
}
