apiVersion: apps/v1
kind: Deployment
metadata:
  name: anki-sync-server
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anki-sync-server
  template:
    metadata:
      labels:
        app: anki-sync-server
    spec:
      containers:
      - name: anki-sync-server
        image: registry.lan.buetow.org:30001/anki-sync-server:25.07.5b
        ports:
        - containerPort: 8080
        env:
        - name: SYNC_PORT
          value: "8080"
        - name: SYNC_USER1
          valueFrom:
            secretKeyRef:
              name: anki-sync-server-secret
              key: SYNC_USER1
        volumeMounts:
        - name: anki-data
          mountPath: /anki_data
      volumes:
      - name: anki-data
        persistentVolumeClaim:
          claimName: anki-data-pvc
