apiVersion: v1
kind: PersistentVolume
metadata:
  name: pkgrepo-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/pkgrepo
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pkgrepo-pvc
  namespace: infra
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pkgrepo-pv
