apiVersion: v1
kind: Service
metadata:
  name: pkgrepo-service
  namespace: infra
spec:
  selector:
    app: pkgrepo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
