// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package pihole

func (Deployment) DescCompose() string {
	return "Installs ~paul/pihole/docker-compose.yml and the LAN wildcard, recreates on change"
}
