theme = "noctis"

[editor]
rulers = [80, 100, 120, 140]
line-number = "relative"
mouse = true
    
[editor.statusline]
left = ["mode", "spinner", "file-name", "position", "version-control"]
center = ["diagnostics"]
right = ["selections", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "underline"
select = "bar"

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end"]

y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"

C-l = ":open ~/.config/helix/languages.toml"
C-c = ":open ~/.config/helix/config.toml"
C-r = ":config-reload"
C-h = ":open ~/Notes/Linux-and-Unix-Tricks/Helix.md"

C-o = [":log-open", "goto_file_end"]
C-q = ":buffer-close"
C-x = [ ":update", ":buffer-close" ]

A-s = { e = ":set-option soft-wrap.enable true", d = ":set-option soft-wrap.enable false" }

# Testing
T = ["save_selection", "goto_file_start", "jump_backward"] 
