// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package openbsd

func (Unattended) DescNewsyslog() string {
	return "Appends unattended-upgrade log rotation to /etc/newsyslog.conf"
}

func (Unattended) DescPing() string { return "Verifies the gonf push pipeline to this host" }

func (Unattended) DescScript() string {
	return "Installs /usr/local/sbin/unattended-upgrade wrapper (0755 root:wheel)"
}

func (Unattended) DescServices() string {
	return "Installs /etc/unattended-upgrade-services (0644 root:wheel)"
}
