# Persistent Volume and Claim for ArgoCD repo-server
# Following the pattern from Loki and Tempo deployments
# Storage: 10Gi at /data/nfs/k3svolumes/argocd/repo-server

apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-repo-server-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/argocd/repo-server
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-repo-server-pvc
  namespace: cicd
spec:
  storageClassName: ""  # Empty for manual binding to PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
