apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/wallabag/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data-pvc
  namespace: services
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wallabag-images-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/wallabag/images
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images-pvc
  namespace: services
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
