// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package rocky

func (Goprecords) DescUpload() string {
	return "Installs the goprecords upload client, token, env file and hourly system timer (oneshot + timer), replacing the hand-made units of the same name when present"
}

func (Goprecords) DescUptimed() string {
	return "Installs the uptimed package, conf (LOG_MAXIMUM_ENTRIES=0), the chronyc waitsync drop-in (no RTC on these Pis), and enables the daemon"
}

func (KernelAudit) DescPackages() string {
	return "Installs ksh, unzip, jq and curl for rocky-kernel-audit"
}

func (KernelAudit) DescScript() string {
	return "Installs /usr/local/sbin/rocky-kernel-audit (0755 root:root)"
}

func (KernelAudit) DescStateDir() string {
	return "Ensures /var/lib/rocky-kernel-audit (feed cache + status)"
}

func (KernelAudit) DescUnits() string {
	return "Installs rocky-kernel-audit SystemdTimer (daily, per-host calendar)"
}

func (Unattended) DescGonfLink() string {
	return "Symlinks /usr/bin/gonf → /usr/local/bin/gonf (sudo secure_path)"
}

func (Unattended) DescLogrotate() string { return "Installs /etc/logrotate.d/unattended-upgrade" }

func (Unattended) DescPackages() string {
	return "Installs ksh + yum-utils (needs-restarting) for unattended-upgrade"
}

func (Unattended) DescScript() string {
	return "Installs /usr/local/sbin/unattended-upgrade-rocky (0755 root:root)"
}

func (Unattended) DescStampDir() string { return "Ensures /var/lib/unattended-upgrade stamp directory" }

func (Unattended) DescTimezone() string {
	return "Sets /etc/localtime to Europe/Sofia (fleet timezone)"
}

func (Unattended) DescUnits() string {
	return "Installs unattended-upgrade-rocky SystemdTimer (oneshot + per-host calendar)"
}
