// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package frontends

func (MailDNS) DescDNSFailover() string {
	return "Installs the frontend DNS failover script and root cron entry"
}

func (Maintenance) DescACME() string {
	return "Installs per-frontend ACME client configuration and daily renewal hook"
}

func (Maintenance) DescBase() string {
	return "Installs frontend base packages and local administration helpers"
}

func (Maintenance) DescGemtexter() string { return "Installs the daily Gemtexter content updater" }

func (Maintenance) DescGoprecords() string {
	return "Installs optional hourly uptimed uploads to goprecords (root cron, output to syslog)"
}

func (Maintenance) DescIRCBouncer() string { return "Installs and enables the fishfinger IRC bouncer" }

func (Maintenance) DescMyname() string { return "Sets each frontend's OpenBSD hostname" }

func (Maintenance) DescRsync() string {
	return "Installs frontend rsync service configuration and synchronization cron"
}

func (Maintenance) DescServiceAccounts() string { return "Creates the disabled Gorum service account" }

func (Maintenance) DescUptimed() string { return "Installs and enables the uptimed service" }

func (Maintenance) DescWireGuardHosts() string {
	return "Appends WireGuard mesh IPv4 and IPv6 host entries"
}

func (Monitoring) DescDTail() string {
	return "Installs DTail from the signed fleet repository and enables dserver"
}

func (Monitoring) DescFoostats() string {
	return "Installs Foostats reporting, dependencies, daily hook, and logs rotation"
}

func (Monitoring) DescGogios() string {
	return "Installs Gogios monitoring, checks, schedules, and status publishing"
}

func (Monitoring) DescPkgRepo() string {
	return "Configures the signed frontend package repository for interactive pkg_add"
}

func (Web) DescACMEInvoke() string { return "Requests and renews frontend ACME certificates" }

func (Web) DescInetd() string { return "Installs and converges frontend inetd" }

func (Web) DescPF() string { return "Validates and reloads frontend PF plus its node_exporter metrics" }
