// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package freebsd

func (Base) DescDoas() string {
	return "Installs doas.conf (nopass :wheel + f3sctl agent rules), validated with doas -C first"
}

func (Base) DescHosts() string {
	return "Renders /etc/hosts (stock header, LAN and wg0 mesh rows from the shared etchosts inventory)"
}

func (Base) DescPackages() string {
	return "Installs the interactive base packages (bash doas git helix jq ksh rsync tmux)"
}

func (Base) DescUptimed() string {
	return "Installs uptimed, its config (LOG_MAXIMUM_ENTRIES=0), enables and runs it; restarts on config change"
}

func (Carp) DescFailbackNewsyslog() string {
	return "Rotates /var/log/carp-auto-failback.log on f0 via /etc/newsyslog.conf"
}

func (Debug) DescGdb() string { return "Installs gdb (kgdb for /var/crash/vmcore.N)" }

func (F3sctl) DescPackage() string {
	return "Installs the f3sctl package (the agent binary /usr/local/bin/f3sctl) from the custom pkg repo"
}

func (F3sctl) DescSSHD() string {
	return "Installs sshd_config (stock + Match User f3sctl block), validated with sshd -t; reloads sshd on change"
}

func (Goprecords) DescUpload() string {
	return "Installs the goprecords upload client, token and hourly root cron (output to syslog)"
}

func (Microcode) DescPackage() string {
	return "Installs cpu-microcode-intel (/boot/firmware/intel-ucode.bin for early loading)"
}

func (Monitoring) DescPackage() string { return "Installs node_exporter" }

func (NFS) DescStunnelPackage() string { return "Installs stunnel on f0/f1" }

func (Periodic) DescTimes() string {
	return "Runs periodic daily/weekly/monthly in each host's afternoon hour (hosts are off at night)"
}

func (RootMail) DescArchive() string {
	return "Archives /var/mail/root to a dated .gz and empties it when above 1 MiB"
}

func (ShellyFans) DescScripts() string {
	return "Installs shelly-fans-on and /usr/local/etc/rc.d/shellyfans (0555 root:wheel; not run)"
}

func (Unattended) DescNewsyslog() string {
	return "Appends unattended-upgrade log rotation to /etc/newsyslog.conf"
}

func (Unattended) DescPackages() string { return "Installs ksh (ksh93) for unattended-upgrade-freebsd" }

func (Unattended) DescRetiredPackages() string {
	return "Removes retired packages (python311 and its py311-* stack)"
}

func (Unattended) DescScript() string {
	return "Installs /usr/local/sbin/unattended-upgrade-freebsd (0755 root:wheel)"
}

func (Unattended) DescServices() string {
	return "Installs /etc/unattended-upgrade-services (0644 root:wheel)"
}

func (Unattended) DescStampDir() string { return "Ensures /var/lib/unattended-upgrade stamp directory" }

func (ZfsKeys) DescScripts() string {
	return "Installs f3s-mount-keys, f3s-load-zfs-keys and /etc/rc.d/f3skeys (0555 root:wheel; not run)"
}

func (Zrepl) DescPackage() string { return "Installs zrepl on the f-hosts" }

func (Zusb) DescScripts() string {
	return "Installs zusb-load and zusb-unload to /usr/local/bin (0755 root:wheel; not run)"
}
