// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package wireguard

func (Mesh) DescInstall() string {
	return "Runs wireguardmeshgenerator --generate --install for the whole mesh (controller-local, explicit only)"
}
