apiVersion: v1
kind: PersistentVolume
metadata:
  name: anki-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/anki-sync-server/anki_data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anki-data-pvc
  namespace: services
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
