// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package netbsd

func (Periodic) DescArchive() string {
	return "Archives /var/mail/root to a dated .gz and empties it when above 1 MiB"
}

func (Periodic) DescLogs() string {
	return "Creates /var/log/daily.log and weekly.log (0640) and rotates them with newsyslog"
}

func (Unattended) DescNewsyslog() string {
	return "Appends unattended-upgrade log rotation to /etc/newsyslog.conf"
}

func (Unattended) DescScript() string {
	return "Installs /usr/local/sbin/unattended-upgrade-netbsd (0755 root:wheel)"
}

func (Unattended) DescServices() string {
	return "Installs /etc/unattended-upgrade-services (0644 root:wheel)"
}

func (Unattended) DescTimezone() string {
	return "Sets /etc/localtime to Europe/Sofia (fleet timezone)"
}

func (Unattended) DescVulnAuditPackages() string { return "Installs curl for netbsd-vuln-audit" }
