package netbsd

import (
	. "github.com/snonux/gonf/api"
	. "github.com/snonux/gonf/api/options"

	"github.com/snonux/conf/gonf/paths"
)

// The WireGuard watchdog for pi0/pi1. The mesh link is the userspace
// wireguard-go daemon behind /etc/rc.d/wireguard (generated by
// wireguardmeshgenerator, not by gonf), and nothing restarted it when it
// died: pi1 sat off the mesh from 2026-09-16 to 2026-09-25. The watchdog is a
// cron job that restarts the rc.d service when the link is broken: daemon
// gone, not answering `wg show`, or tun0 down.
//
// Like VulnAudit*, the tasks are methods of Unattended so they register as
// pis_netbsd_wireguard_watchdog_* and join the pis_netbsd aggregate through
// the existing registration.
const wireguardWatchdogScript = "/usr/local/sbin/wireguard-watchdog"

// DescWireguardWatchdogScript returns the description for the script.
func (Unattended) DescWireguardWatchdogScript() string {
	return "Install " + wireguardWatchdogScript + " (0755 root:wheel)"
}

// WireguardWatchdogScript installs the watchdog (after its directory, which
// gonf orders as the parent).
func (Unattended) WireguardWatchdogScript() {
	EnsureDir("/usr/local/sbin", Perm(0o755, Root))
	InstallFile(wireguardWatchdogScript,
		paths.GonfAsset("netbsd", "wireguard-watchdog"),
		Perm(0o755, Root))
}

// DescWireguardWatchdogCron returns the description for the cron job.
func (Unattended) DescWireguardWatchdogCron() string {
	return "Root cron: wireguard-watchdog every 5 minutes"
}

// OptsWireguardWatchdogCron records the script before the job. Privileged()
// is repeated because the per-method companion replaces the RequiresRoot
// struct default.
func (Unattended) OptsWireguardWatchdogCron() TaskOptions {
	return TaskOptions{Privileged(), Needs("wireguard_watchdog_script")}
}

// WireguardWatchdogCron checks the link every five minutes: a dead link is
// back within five minutes, and a healthy one costs a pgrep, a `wg show` and
// an ifconfig per run.
func (Unattended) WireguardWatchdogCron() {
	CronAt("wireguard-watchdog", "*/5 * * * *", wireguardWatchdogScript)
}
