NAMESPACE := "services"
RELEASE_NAME := "filerise"
CHART_PATH := "./helm-chart"

install:
    helm install {{RELEASE_NAME}} {{CHART_PATH}} --namespace {{NAMESPACE}} --create-namespace

upgrade:
    helm upgrade {{RELEASE_NAME}} {{CHART_PATH}} --namespace {{NAMESPACE}}

delete:
    helm uninstall {{RELEASE_NAME}} --namespace {{NAMESPACE}}
    kubectl delete pvc filerise-uploads-pvc filerise-users-pvc filerise-metadata-pvc -n {{NAMESPACE}} --ignore-not-found
    kubectl delete pv filerise-uploads-pv filerise-users-pv filerise-metadata-pv --ignore-not-found

deinstall: delete
