apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@git-server.cicd.svc.cluster.local/repos/repos/conf.git
    targetRevision: master
    path: f3s/registry/helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
