apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-server-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nfs/k3svolumes/git-server
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-server-pvc
  namespace: cicd
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
