apiVersion: v1
kind: Service
metadata:
  labels:
    app: syncthing
  name: syncthing-service
  namespace: services
spec:
  ports:
    - name: web
      port: 8384
      protocol: TCP
      targetPort: 8384
    - name: data
      port: 22000
      protocol: TCP
      targetPort: 22000
  selector:
    app: syncthing
