// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package garage

func (Deployment) DescConfig() string {
	return "Renders and installs Garage TOML on f0, f1, and f2 (config only; Garage must already be installed and provisioned)"
}
