apiVersion: v1
kind: Service
metadata:
  labels:
    app: opodsync
  name: opodsync-service
  namespace: services
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: opodsync
