# frozen_string_literal: true

require "#{ENV['HOME']}/git/rcm/lib/dsl"

desc 'Improve english'
task :english do
  configure do
    agent hexai do
      'hexai PROMPT'
    end

    agent gpt20b do
      'ollama run gpt-oss:20b --hidethinking PROMPT'
    end

    agent gpt120b do
      ENV['OLLAMA_HOST'] = 'http://hyperstack.wg1:11434'
      'ollama run gpt-oss:120b --hidethinking PROMPT'
    end

    prompt improve blog english do
      <<~TEXT
        This is text from my blog in Gemini Gemtext format plus extra tags.
        Don't remove or modify any lines starting with any of those characters: < > # ` *
        Correct English spellings and grammar. Improve clarity of the text.
        Don't introduce any new text or headers. Don't modify any source code text unless code comments.
        Only point out the corrections you would someone to implement.
      TEXT
    end

    blog_contents = Dir.glob(File.expand_path('~/git/foo.zone-content/gemtext/**/*.gmi')).map do |gmi|
      File.exist?("#{gmi}.tpl") ? "#{gmi}.tpl" : gmi
    end

    blog_contents.each do |blog_content|
      file blog_content do
        agent gpt120b improve blog english
      end
    end
  end
end
