apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      securityContext:
        runAsUser: 65534        # nobody
        runAsGroup: 65534       # nobody / nogroup
        fsGroup: 65534          # ensure mounted volumes are group-writable
        runAsNonRoot: true
      containers:
      - name: freshrss
        image: freshrss/freshrss:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: freshrss-data
            mountPath: /var/www/FreshRSS/data
      volumes:
      - name: freshrss-data
        persistentVolumeClaim:
          claimName: freshrss-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: freshrss
  name: freshrss-service
  namespace: services
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: freshrss
